version: "3.9"
services:
  api_solarys:
    build:
      context: ./app
      dockerfile: ../Dockerfile
    ports:
      - "3333:3333"
    networks:
      - solarys_network
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_solarys
    networks:
      - solarys_network
    restart: unless-stopped
networks:
  solarys_network:
    driver: bridge