version: "3.9"
services:
  api_solarys:
    build:
      context: ./app
      dockerfile: ../Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health-check"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - solarys_network
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_solarys
    networks:
      - solarys_network
    restart: unless-stopped
networks:
  solarys_network:
    driver: bridge